name: Publish Addon Image

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
      publish-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: "Install nix"
            uses: cachix/install-nix-action@v27

          - name: "Build Image"
            run: nix build .#containers.hass-addon.aarch64-linux

          - name: "Load Image"
            run: docker load < result

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3.1.0
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Push Image'
            run: docker push ghcr.io/seineeloquenz/dyndns-netcup:${{ github.ref_name }}
